### ISSUE TITLE
Add WiNLP papers

### ISSUE THREAD

**Issue by juliakreutzer** [masakhane-io/masakhane-community#10]
They're currently missing from publications.md.

**Comment by juliakreutzer** [comment]
https://arxiv.org/abs/2006.09217

**Comment by WalePhenomenon** [comment]
1. https://www.aclweb.org/anthology/2020.winlp-1.38/
2. https://www.aclweb.org/anthology/2020.winlp-1.26/

No 2 is not Masakhane MT related but I added it because it's NLP for Africa :)

**Comment by bonaventuredossou** [comment]
1. ACL Anthology: https://www.aclweb.org/anthology/2020.winlp-1.21/

**Comment by Witty-Kitty** [comment]
https://www.aclweb.org/anthology/2020.winlp-1.18/

**Comment by juliakreutzer** [comment]
@Witty-Kitty added, thanks!
